-- MySQL Script generated by MySQL Workbench
-- Sat Dec 10 21:11:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProciDataBase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProciDataBase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProciDataBase` DEFAULT CHARACTER SET utf8 ;
USE `ProciDataBase` ;

-- -----------------------------------------------------
-- Table `ProciDataBase`.`clasificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProciDataBase`.`clasificacion` (
  `idClasificacion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClasificacion`),
  UNIQUE INDEX `idClasificacion_UNIQUE` (`idClasificacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProciDataBase`.`tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProciDataBase`.`tienda` (
  `idTienda` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTienda`),
  UNIQUE INDEX `idTienda_UNIQUE` (`idTienda` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProciDataBase`.`unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProciDataBase`.`unidad` (
  `idunidad` INT NOT NULL,
  `unidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idunidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProciDataBase`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProciDataBase`.`area` (
  `idarea` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idarea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProciDataBase`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProciDataBase`.`empleado` (
  `idempleado` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL DEFAULT '',
  `telefono` VARCHAR(10) NOT NULL,
  `email` TEXT(100) NOT NULL DEFAULT 'No registrado',
  `idArea` INT NOT NULL,
  PRIMARY KEY (`idempleado`),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `idArea_idx` (`idArea` ASC) VISIBLE,
  CONSTRAINT `idArea`
    FOREIGN KEY (`idArea`)
    REFERENCES `ProciDataBase`.`area` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProciDataBase`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProciDataBase`.`cuenta` (
  `idcuenta` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `contraseña` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`idcuenta`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`idcuenta`)
    REFERENCES `ProciDataBase`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProciDataBase`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProciDataBase`.`inventario` (
  `id_inventario` INT NOT NULL AUTO_INCREMENT,
  `material` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `unidad` INT NOT NULL,
  `fecha_ingreso` DATETIME NOT NULL,
  `limite_minimo` INT NOT NULL,
  `id_clasificacion` INT NOT NULL,
  `SKU` VARCHAR(100) NOT NULL,
  `tienda` INT NOT NULL,
  `pedido_por` INT NOT NULL,
  PRIMARY KEY (`id_inventario`),
  UNIQUE INDEX `material_UNIQUE` (`material` ASC) VISIBLE,
  INDEX `id_clasificacion_idx` (`id_clasificacion` ASC) VISIBLE,
  INDEX `tienda_idx` (`tienda` ASC) VISIBLE,
  INDEX `unidad_idx` (`unidad` ASC) VISIBLE,
  INDEX `usuario_idx` (`pedido_por` ASC) VISIBLE,
  CONSTRAINT `id_clasificacion`
    FOREIGN KEY (`id_clasificacion`)
    REFERENCES `ProciDataBase`.`clasificacion` (`idClasificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tienda`
    FOREIGN KEY (`tienda`)
    REFERENCES `ProciDataBase`.`tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `unidad`
    FOREIGN KEY (`unidad`)
    REFERENCES `ProciDataBase`.`unidad` (`idunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario`
    FOREIGN KEY (`pedido_por`)
    REFERENCES `ProciDataBase`.`cuenta` (`idcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProciDataBase`.`salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProciDataBase`.`salida` (
  `id_salida` INT NOT NULL AUTO_INCREMENT,
  `empleado` INT NOT NULL,
  `area` INT NOT NULL,
  `material` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `id_unidad` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `id_usuario` INT NOT NULL,
  `concepto` TEXT(150) NOT NULL,
  PRIMARY KEY (`id_salida`),
  INDEX `empleado_idx` (`empleado` ASC) VISIBLE,
  INDEX `area_empleado_idx` (`area` ASC) VISIBLE,
  INDEX `material_idx` (`material` ASC) VISIBLE,
  UNIQUE INDEX `id_salida_UNIQUE` (`id_salida` ASC) VISIBLE,
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `unidad_idx` (`id_unidad` ASC) VISIBLE,
  CONSTRAINT `empleado`
    FOREIGN KEY (`empleado`)
    REFERENCES `ProciDataBase`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `area_empleado`
    FOREIGN KEY (`area`)
    REFERENCES `ProciDataBase`.`empleado` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `material`
    FOREIGN KEY (`material`)
    REFERENCES `ProciDataBase`.`inventario` (`material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `unidad`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `ProciDataBase`.`inventario` (`unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ProciDataBase`.`cuenta` (`idcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
